-- La landing usa la tabla: public.pedidos
-- Columnas esperadas:
-- telefono, ciudad, barrio, direccion, producto, cantidad,
-- precio_unitario, total, observaciones
-- El nombre del cliente se guarda dentro de observaciones para no exigir
-- una columna adicional si tu tabla actual no tiene 'nombre'.

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  telefono text,
  ciudad text,
  barrio text,
  direccion text,
  producto text,
  cantidad integer,
  precio_unitario numeric,
  total numeric,
  observaciones text
);

alter table public.pedidos enable row level security;

drop policy if exists "permitir registrar pedidos desde landing" on public.pedidos;
create policy "permitir registrar pedidos desde landing"
on public.pedidos
for insert
to anon
with check (true);
